
package org.hyperimage.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HIEditorService", targetNamespace = "http://ws.service.hyperimage.org/", wsdlLocation = "http://localhost:8080/HI3Author/HIEditorService?wsdl")
public class HIEditorService
    extends Service
{

    private final static URL HIEDITORSERVICE_WSDL_LOCATION;
    private final static WebServiceException HIEDITORSERVICE_EXCEPTION;
    private final static QName HIEDITORSERVICE_QNAME = new QName("http://ws.service.hyperimage.org/", "HIEditorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/HI3Author/HIEditorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HIEDITORSERVICE_WSDL_LOCATION = url;
        HIEDITORSERVICE_EXCEPTION = e;
    }

    public HIEditorService() {
        super(__getWsdlLocation(), HIEDITORSERVICE_QNAME);
    }

    public HIEditorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HIEDITORSERVICE_QNAME, features);
    }

    public HIEditorService(URL wsdlLocation) {
        super(wsdlLocation, HIEDITORSERVICE_QNAME);
    }

    public HIEditorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HIEDITORSERVICE_QNAME, features);
    }

    public HIEditorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HIEditorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HIEditor
     */
    @WebEndpoint(name = "HIEditorPort")
    public HIEditor getHIEditorPort() {
        return super.getPort(new QName("http://ws.service.hyperimage.org/", "HIEditorPort"), HIEditor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HIEditor
     */
    @WebEndpoint(name = "HIEditorPort")
    public HIEditor getHIEditorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service.hyperimage.org/", "HIEditorPort"), HIEditor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HIEDITORSERVICE_EXCEPTION!= null) {
            throw HIEDITORSERVICE_EXCEPTION;
        }
        return HIEDITORSERVICE_WSDL_LOCATION;
    }

}
