
package org.hyperimage.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HIEntityException", targetNamespace = "http://ws.service.hyperimage.org/")
public class HIEntityException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HIEntityException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public HIEntityException_Exception(String message, HIEntityException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public HIEntityException_Exception(String message, HIEntityException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hyperimage.client.ws.HIEntityException
     */
    public HIEntityException getFaultInfo() {
        return faultInfo;
    }

}
