
package org.hyperimage.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import javax.xml.ws.wsaddressing.W3CEndpointReference;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HILogin", targetNamespace = "http://ws.service.hyperimage.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HILogin {


    /**
     * 
     * @param editorRef
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.LogoutResponse")
    @Action(input = "http://ws.service.hyperimage.org/HILogin/logoutRequest", output = "http://ws.service.hyperimage.org/HILogin/logoutResponse")
    public boolean logout(
        @WebParam(name = "editorRef", targetNamespace = "")
        W3CEndpointReference editorRef);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPPGLocation", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.GetPPGLocation")
    @ResponseWrapper(localName = "getPPGLocationResponse", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.GetPPGLocationResponse")
    @Action(input = "http://ws.service.hyperimage.org/HILogin/getPPGLocationRequest", output = "http://ws.service.hyperimage.org/HILogin/getPPGLocationResponse")
    public String getPPGLocation();

    /**
     * 
     * @param userID
     * @param tokenVerifier
     * @param token
     * @param tokenSecret
     * @return
     *     returns javax.xml.ws.wsaddressing.W3CEndpointReference
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticatePR", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.AuthenticatePR")
    @ResponseWrapper(localName = "authenticatePRResponse", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.AuthenticatePRResponse")
    @Action(input = "http://ws.service.hyperimage.org/HILogin/authenticatePRRequest", output = "http://ws.service.hyperimage.org/HILogin/authenticatePRResponse")
    public W3CEndpointReference authenticatePR(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "tokenSecret", targetNamespace = "")
        String tokenSecret,
        @WebParam(name = "tokenVerifier", targetNamespace = "")
        String tokenVerifier,
        @WebParam(name = "userID", targetNamespace = "")
        String userID);

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns javax.xml.ws.wsaddressing.W3CEndpointReference
     * @throws HIParameterException_Exception
     * @throws HIMaintenanceModeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.AuthenticateResponse")
    @Action(input = "http://ws.service.hyperimage.org/HILogin/authenticateRequest", output = "http://ws.service.hyperimage.org/HILogin/authenticateResponse", fault = {
        @FaultAction(className = HIParameterException_Exception.class, value = "http://ws.service.hyperimage.org/HILogin/authenticate/Fault/HIParameterException"),
        @FaultAction(className = HIMaintenanceModeException_Exception.class, value = "http://ws.service.hyperimage.org/HILogin/authenticate/Fault/HIMaintenanceModeException")
    })
    public W3CEndpointReference authenticate(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws HIMaintenanceModeException_Exception, HIParameterException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersionID", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.GetVersionID")
    @ResponseWrapper(localName = "getVersionIDResponse", targetNamespace = "http://ws.service.hyperimage.org/", className = "org.hyperimage.client.ws.GetVersionIDResponse")
    @Action(input = "http://ws.service.hyperimage.org/HILogin/getVersionIDRequest", output = "http://ws.service.hyperimage.org/HILogin/getVersionIDResponse")
    public String getVersionID();

}
