
package org.hyperimage.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HIMaintenanceModeException", targetNamespace = "http://ws.service.hyperimage.org/")
public class HIMaintenanceModeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HIMaintenanceModeException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public HIMaintenanceModeException_Exception(String message, HIMaintenanceModeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public HIMaintenanceModeException_Exception(String message, HIMaintenanceModeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hyperimage.client.ws.HIMaintenanceModeException
     */
    public HIMaintenanceModeException getFaultInfo() {
        return faultInfo;
    }

}
