
package org.hyperimage.client.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HIParameterException", targetNamespace = "http://ws.service.hyperimage.org/")
public class HIParameterException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HIParameterException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public HIParameterException_Exception(String message, HIParameterException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public HIParameterException_Exception(String message, HIParameterException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hyperimage.client.ws.HIParameterException
     */
    public HIParameterException getFaultInfo() {
        return faultInfo;
    }

}
