
package info.fedora.definitions._1._0.api;

import java.math.BigInteger;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import info.fedora.definitions._1._0.types.ArrayOfString;
import info.fedora.definitions._1._0.types.DatastreamDef;
import info.fedora.definitions._1._0.types.FieldSearchQuery;
import info.fedora.definitions._1._0.types.FieldSearchResult;
import info.fedora.definitions._1._0.types.MIMETypedStream;
import info.fedora.definitions._1._0.types.ObjectFactory;
import info.fedora.definitions._1._0.types.ObjectMethodsDef;
import info.fedora.definitions._1._0.types.ObjectProfile;
import info.fedora.definitions._1._0.types.RepositoryInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2_01-hudson-189-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Fedora-API-A", targetNamespace = "http://www.fedora.info/definitions/1/0/api/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FedoraAPIA {


    /**
     * 
     * @return
     *     returns info.fedora.definitions._1._0.types.RepositoryInfo
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#describeRepository")
    @WebResult(name = "repositoryInfo", targetNamespace = "")
    @RequestWrapper(localName = "describeRepository", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.DescribeRepository")
    @ResponseWrapper(localName = "describeRepositoryResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.DescribeRepositoryResponse")
    public RepositoryInfo describeRepository();

    /**
     * 
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns info.fedora.definitions._1._0.types.ObjectProfile
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getObjectProfile")
    @WebResult(name = "objectProfile", targetNamespace = "")
    @RequestWrapper(localName = "getObjectProfile", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.GetObjectProfile")
    @ResponseWrapper(localName = "getObjectProfileResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.GetObjectProfileResponse")
    public ObjectProfile getObjectProfile(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns java.util.List<info.fedora.definitions._1._0.types.ObjectMethodsDef>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#listMethods")
    @WebResult(name = "objectMethod", targetNamespace = "")
    @RequestWrapper(localName = "listMethods", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.ListMethods")
    @ResponseWrapper(localName = "listMethodsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.ListMethodsResponse")
    public List<ObjectMethodsDef> listMethods(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns java.util.List<info.fedora.definitions._1._0.types.DatastreamDef>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#listDatastreams")
    @WebResult(name = "datastreamDef", targetNamespace = "")
    @RequestWrapper(localName = "listDatastreams", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.ListDatastreams")
    @ResponseWrapper(localName = "listDatastreamsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.ListDatastreamsResponse")
    public List<DatastreamDef> listDatastreams(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param asOfDateTime
     * @param dsID
     * @param pid
     * @return
     *     returns info.fedora.definitions._1._0.types.MIMETypedStream
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getDatastreamDissemination")
    @WebResult(name = "dissemination", targetNamespace = "")
    @RequestWrapper(localName = "getDatastreamDissemination", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.GetDatastreamDissemination")
    @ResponseWrapper(localName = "getDatastreamDisseminationResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.GetDatastreamDisseminationResponse")
    public MIMETypedStream getDatastreamDissemination(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param parameters
     * @param asOfDateTime
     * @param bDefPid
     * @param pid
     * @param methodName
     * @return
     *     returns info.fedora.definitions._1._0.types.MIMETypedStream
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getDissemination")
    @WebResult(name = "dissemination", targetNamespace = "")
    @RequestWrapper(localName = "getDissemination", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.GetDissemination")
    @ResponseWrapper(localName = "getDisseminationResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.GetDisseminationResponse")
    public MIMETypedStream getDissemination(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "bDefPid", targetNamespace = "")
        String bDefPid,
        @WebParam(name = "methodName", targetNamespace = "")
        String methodName,
        @WebParam(name = "parameters", targetNamespace = "")
        info.fedora.definitions._1._0.types.GetDissemination.Parameters parameters,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param query
     * @param maxResults
     * @param resultFields
     * @return
     *     returns info.fedora.definitions._1._0.types.FieldSearchResult
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#findObjects")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "findObjects", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.FindObjects")
    @ResponseWrapper(localName = "findObjectsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.FindObjectsResponse")
    public FieldSearchResult findObjects(
        @WebParam(name = "resultFields", targetNamespace = "")
        ArrayOfString resultFields,
        @WebParam(name = "maxResults", targetNamespace = "")
        BigInteger maxResults,
        @WebParam(name = "query", targetNamespace = "")
        FieldSearchQuery query);

    /**
     * 
     * @param sessionToken
     * @return
     *     returns info.fedora.definitions._1._0.types.FieldSearchResult
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#resumeFindObjects")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "resumeFindObjects", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.ResumeFindObjects")
    @ResponseWrapper(localName = "findObjectsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.FindObjectsResponse")
    public FieldSearchResult resumeFindObjects(
        @WebParam(name = "sessionToken", targetNamespace = "")
        String sessionToken);

    /**
     * 
     * @param pid
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getObjectHistory")
    @WebResult(name = "modifiedDate", targetNamespace = "")
    @RequestWrapper(localName = "getObjectHistory", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.GetObjectHistory")
    @ResponseWrapper(localName = "getObjectHistoryResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "info.fedora.definitions._1._0.types.GetObjectHistoryResponse")
    public List<String> getObjectHistory(
        @WebParam(name = "pid", targetNamespace = "")
        String pid);

}
