/*
 * Copyright 2015 bitGilde IT Solutions UG (haftungsbeschränkt)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *  http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.hyperimage.client.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import org.hyperimage.client.gui.lists.TagListCellRenderer;
import org.hyperimage.client.ws.HiGroup;

/**
 *
 * @author Jens-Martin Loebel <loebel@bitgilde.de>
 */
public class VisualTag extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    private HiGroup tag;
    
    /**
     * Creates new VisualTag
     * @param tag
     * @param listener ActionListener for remove tag button
     */
    public VisualTag(HiGroup tag, ActionListener listener) {
        this.tag = tag;
        initComponents();
        
        this.removeTagButton.addActionListener(listener);
        this.tagButton.setText(TagListCellRenderer.getTagName(tag));
        this.tagButton.setBorder(null);
        this.tagButton.setBackground(new Color(102, 153, 238));

    }

    
    public HiGroup getModel() {
        return this.tag;
    }
    
    @Override
    public String toString() {
        return this.tag.toString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeTagButton = new JButton();
        tagButton = new JButton();

        setBackground(new Color(102, 153, 238));
        setBorder(new LineBorder(new Color(0, 153, 255), 2, true));

        removeTagButton.setFont(removeTagButton.getFont().deriveFont(removeTagButton.getFont().getStyle() | Font.BOLD));
        removeTagButton.setText("x");
        removeTagButton.setBorder(null);
        removeTagButton.setHorizontalTextPosition(SwingConstants.CENTER);
        removeTagButton.setPreferredSize(new Dimension(24, 18));

        tagButton.setFont(new Font("Lucida Grande", 1, 13)); // NOI18N
        tagButton.setForeground(Color.white);
        tagButton.setText("Tag");
        tagButton.setBorder(null);
        tagButton.setHorizontalAlignment(SwingConstants.RIGHT);
        tagButton.setHorizontalTextPosition(SwingConstants.CENTER);
        tagButton.setPreferredSize(new Dimension(24, 18));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tagButton, GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeTagButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(removeTagButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(tagButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton removeTagButton;
    private JButton tagButton;
    // End of variables declaration//GEN-END:variables
}
