
package org.hyperimage.connector.fedora3.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-749-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HIFedora3Connector", targetNamespace = "http://fedora3.connector.hyperimage.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HIFedora3Connector {


    /**
     * 
     * @param username
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.AuthenticateResponse")
    public void authenticate(
        @WebParam(name = "username", targetNamespace = "http://connector.ws.hyperimage.org/")
        String username,
        @WebParam(name = "token", targetNamespace = "http://connector.ws.hyperimage.org/")
        String token);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWSVersion", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetWSVersion")
    @ResponseWrapper(localName = "getWSVersionResponse", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetWSVersionResponse")
    public String getWSVersion();

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws HIWSLoggedException_Exception
     * @throws HIWSAuthException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReposInfo", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetReposInfo")
    @ResponseWrapper(localName = "getReposInfoResponse", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetReposInfoResponse")
    public String getReposInfo()
        throws HIWSAuthException_Exception, HIWSLoggedException_Exception
    ;

    /**
     * 
     * @param assetURN
     * @param session
     * @return
     *     returns org.hyperimage.connector.fedora3.ws.HiTypedDatastream
     * @throws HIWSNotBinaryException_Exception
     * @throws HIWSLoggedException_Exception
     * @throws HIWSAuthException_Exception
     * @throws HIWSAssetNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssetData", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetAssetData")
    @ResponseWrapper(localName = "getAssetDataResponse", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetAssetDataResponse")
    public HiTypedDatastream getAssetData(
        @WebParam(name = "session", targetNamespace = "http://connector.ws.hyperimage.org/")
        String session,
        @WebParam(name = "assetURN", targetNamespace = "http://connector.ws.hyperimage.org/")
        String assetURN)
        throws HIWSAssetNotFoundException_Exception, HIWSAuthException_Exception, HIWSLoggedException_Exception, HIWSNotBinaryException_Exception
    ;

    /**
     * 
     * @param assetURN
     * @param session
     * @return
     *     returns byte[]
     * @throws HIWSNotBinaryException_Exception
     * @throws HIWSLoggedException_Exception
     * @throws HIWSAuthException_Exception
     * @throws HIWSAssetNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssetPreviewData", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetAssetPreviewData")
    @ResponseWrapper(localName = "getAssetPreviewDataResponse", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetAssetPreviewDataResponse")
    public byte[] getAssetPreviewData(
        @WebParam(name = "session", targetNamespace = "http://connector.ws.hyperimage.org/")
        String session,
        @WebParam(name = "assetURN", targetNamespace = "http://connector.ws.hyperimage.org/")
        String assetURN)
        throws HIWSAssetNotFoundException_Exception, HIWSAuthException_Exception, HIWSLoggedException_Exception, HIWSNotBinaryException_Exception
    ;

    /**
     * 
     * @param assetURN
     * @param session
     * @return
     *     returns java.util.List<org.hyperimage.connector.fedora3.ws.HiMetadataRecord>
     * @throws HIWSDCMetadataException_Exception
     * @throws HIWSLoggedException_Exception
     * @throws HIWSXMLParserException_Exception
     * @throws HIWSUTF8EncodingException_Exception
     * @throws HIWSAssetNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMetadataRecord", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetMetadataRecord")
    @ResponseWrapper(localName = "getMetadataRecordResponse", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetMetadataRecordResponse")
    public List<HiMetadataRecord> getMetadataRecord(
        @WebParam(name = "session", targetNamespace = "http://connector.ws.hyperimage.org/")
        String session,
        @WebParam(name = "assetURN", targetNamespace = "http://connector.ws.hyperimage.org/")
        String assetURN)
        throws HIWSAssetNotFoundException_Exception, HIWSDCMetadataException_Exception, HIWSLoggedException_Exception, HIWSUTF8EncodingException_Exception, HIWSXMLParserException_Exception
    ;

    /**
     * 
     * @param parentURN
     * @param session
     * @return
     *     returns java.util.List<org.hyperimage.connector.fedora3.ws.HiHierarchyLevel>
     * @throws HIWSLoggedException_Exception
     * @throws HIWSAuthException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHierarchyLevel", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetHierarchyLevel")
    @ResponseWrapper(localName = "getHierarchyLevelResponse", targetNamespace = "http://fedora3.connector.hyperimage.org/", className = "org.hyperimage.connector.fedora3.ws.GetHierarchyLevelResponse")
    public List<HiHierarchyLevel> getHierarchyLevel(
        @WebParam(name = "session", targetNamespace = "http://connector.ws.hyperimage.org/")
        String session,
        @WebParam(name = "parentURN", targetNamespace = "http://connector.ws.hyperimage.org/")
        String parentURN)
        throws HIWSAuthException_Exception, HIWSLoggedException_Exception
    ;

}
