
package org.hyperimage.connector.fedora3.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-749-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HIFedora3ConnectorService", targetNamespace = "http://fedora3.connector.hyperimage.org/", wsdlLocation = "http://localhost:8080/HIFedora3Connector/HIFedora3ConnectorService?wsdl")
public class HIFedora3ConnectorService
    extends Service
{

    private final static URL HIFEDORA3CONNECTORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.hyperimage.connector.fedora3.ws.HIFedora3ConnectorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.hyperimage.connector.fedora3.ws.HIFedora3ConnectorService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/HIFedora3Connector/HIFedora3ConnectorService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/HIFedora3Connector/HIFedora3ConnectorService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HIFEDORA3CONNECTORSERVICE_WSDL_LOCATION = url;
    }

    public HIFedora3ConnectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HIFedora3ConnectorService() {
        super(HIFEDORA3CONNECTORSERVICE_WSDL_LOCATION, new QName("http://fedora3.connector.hyperimage.org/", "HIFedora3ConnectorService"));
    }

    /**
     * 
     * @return
     *     returns HIFedora3Connector
     */
    @WebEndpoint(name = "HIFedora3ConnectorPort")
    public HIFedora3Connector getHIFedora3ConnectorPort() {
        return super.getPort(new QName("http://fedora3.connector.hyperimage.org/", "HIFedora3ConnectorPort"), HIFedora3Connector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HIFedora3Connector
     */
    @WebEndpoint(name = "HIFedora3ConnectorPort")
    public HIFedora3Connector getHIFedora3ConnectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedora3.connector.hyperimage.org/", "HIFedora3ConnectorPort"), HIFedora3Connector.class, features);
    }

}
